name: Dictionary

on:
  schedule:
    - cron: 0 12 3 * *
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.time.outputs.version }}
    steps:
      - name: Decide version
        env:
          TZ: 'Asia/Tokyo'
        id: time
        run: |
          if [ "$(date +'%d')" -gt 20 ]; then
            day=20
          else
            day=01
          fi

          echo "version=$(date +'%Y%m')$day" >> "$GITHUB_OUTPUT"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete -R ${{ github.repository }} ${{ steps.time.outputs.version }} -y --cleanup-tag || true
          gh release create -R ${{ github.repository }} ${{ steps.time.outputs.version }} -d -t ${{ steps.time.outputs.version }} -n 'These XTBook dictionary files (.xtbdict) are automatically created from the version ${{ steps.time.outputs.version }}. **You must extract them with an extractor such as `tar` or [7-Zip](http://www.7-zip.org/) before using them on the XTBook.** For 7-Zip, download all splitted files and specify to extract the first archive. For `tar`, concatenate all splitted files with `tarcat` and pipe them to `tar`. You may find some MediaWiki based wikis that are not distributed below, such as images for Japanese Uncyclopedia, Brain Wiki, and English Wikipedia at [OSDN](https://osdn.net/projects/xtbook/). Open an [issue](https://github.com/watamario15/xtbook/issues) for Wikimedia wikis that are not currently listed here. License information can be found [here](https://ja.osdn.net/projects/xtbook/wiki/FrontPage).

          ${{ steps.time.outputs.version }} の版を元に自動生成された XTBook 辞書ファイル (.xtbdict) です。**ダウンロードしたファイルは、最初に `tar` や [7-Zip](https://sevenzip.osdn.jp/) 等を用いて展開する必要があります。**7-Zip なら分割ファイル全てをダウンロードし、最初の番号のファイルを指定して展開します。`tar` の場合は `tarcat` を用いて全てを結合し、それをパイプで `tar` に流して展開します。Uncyclopedia 日本語版の画像データ、Brain Wiki、英語版 Wikipedia は自動化できないため、[OSDN](https://ja.osdn.net/projects/xtbook/) で手動配布しています。Wikimedia 財団の wiki のうち、生成していないものについては [issue](https://github.com/watamario15/xtbook/issues) を立ててもらえれば検討します。ライセンス情報は[こちら](https://ja.osdn.net/projects/xtbook/wiki/FrontPage)から確認してください。'

  dictgen:
    name: Convert
    needs: [create_release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wiki: [
            jawiki,
            jawikibooks,
            jawikinews,
            jawikiquote,
            jawikisource,
            jawiktionary,
            eowiki,
            specieswiki
          ] # enwiki is too big to build on GitHub Actions
    steps:
      - name: Prepare
        run: |
          curl -sSfLO https://github.com/watamario15/xtbook/releases/download/v0.2.6/xtbookconv.7z
          7z x xtbookconv.7z
          curl -sSfLO https://github.com/watamario15/dotfiles/raw/main/tools/info-plists/${{ matrix.wiki }}.plist
          curl -sSfLO https://github.com/watamario15/dotfiles/raw/main/tools/xtbconv
          chmod +x xtbconv
          sudo apt install -y mecab-ipadic libmecab2 libkakasi2

      - name: Convert
        run: |
          export PATH=${{ github.workspace }}:$PATH
          export DICTDIR=${{ github.workspace }}
          export PLIST=${{ github.workspace }}
          ./xtbconv wikimedia ${{ matrix.wiki }} ${{ needs.create_release.outputs.version }} 1900M

      - name: Upload
        run: gh release upload -R ${{ github.repository }} ${{ steps.time.outputs.version }} ./*.xtbdict.tar.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    needs: [create_release, dictgen]
    runs-on: ubuntu-latest
    steps:
      - name: Publish the draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit -R ${{ github.repository }} ${{ steps.time.outputs.version }} --draft=false
